```{r}
library(tidyverse)
library(scales)
library(RColorBrewer)
library(viridis)
library(moments)

caption <- "Max Woolf — minimaxir.com"

sessionInfo()
```
```{r}
theme_set(theme_minimal(base_size = 8, base_family = "Overpass") +
  theme(
    plot.title = element_text(size = 8, face = "bold"),
    plot.subtitle = element_text(color = "#666666", size = 6),
    axis.title.x = element_text(size = 6),
    axis.title.y = element_text(size = 6),
    plot.caption = element_text(size = 5, color = "#969696"),
    plot.background = element_rect(fill = "#FFFFFF"),
    legend.title = element_text(size = 8),
    legend.key.width = unit(0.25, unit = "cm"),
    panel.grid.minor = element_blank()
  ))
```

```{r}
df <- read_csv("tip_trials.csv") %>%
  bind_rows(read_csv("tip_trials_adv.csv"))
df %>% head()
```

```{r}
null_dist <- df %>%
  filter(label == "<no tip>") %>%
  pull(output_len)

df_agg <- df %>%
  mutate(label = factor(label)) %>%
  group_by(label) %>%
  summarize(
    avg = mean(output_len),
    std = sd(output_len),
    mse = mean((output_len - 200)^2),
    pval = ks.test(output_len, null_dist)$p.value,
    skew = skewness(output_len),
    kurt = kurtosis(output_len)
  )

df_agg
```

```{r}
palette <- brewer.pal(7, "Set1")
palette
```

## Base Distribution of Character Counts

```{r}
labels <- c(
  "<no tip>" = palette[1]
)

df_subset <- df %>%
  filter(label %in% names(labels)) %>%
  mutate(label = factor(label, levels = names(labels)))

df_agg_subset <- df_agg %>%
  filter(label %in% names(labels))

plot <- ggplot(df_subset, aes(output_len, fill = label)) +
  geom_histogram(binwidth = 10) +
  geom_label(
    data = df_agg_subset, mapping = aes(label = sprintf("x̄ = %s\nMSE = %s", round(avg), round(mse)), color = label, x = 20, y = Inf),
    vjust = 1.1, hjust = 0, fill = "white",
    family = "Overpass",
    size = 2, lineheight = 1.0, label.padding = unit(0.10, "cm"), label.size = 0.3,
  ) +
  scale_x_continuous(limits = c(0, 400)) +
  geom_vline(xintercept = 200, color = "#1a1a1a") +
  scale_fill_manual(values = labels, guide = "none") +
  scale_color_manual(values = labels, guide = "none") +
  labs(
    title = "Character Lengths of ChatGPT Output Without Tip Incentive",
    subtitle = "100 generations each, targeting 200 characters. gpt-3.5-turbo-0125, temperature = 1",
    x = "Character Length of Generation", y = "# of Generations",
    caption = caption
  )

ggsave("tips_hist_notip.png", plot, width = 4, height = 2)
```

```{r}
labels <- c(
  "$500 tip" = palette[2],
  "$1,000 tip" = palette[3],
  "$100,000 bonus" = palette[4]
)

df_subset <- df %>%
  filter(label %in% names(labels)) %>%
  mutate(label = factor(label, levels = names(labels)))

df_agg_subset <- df_agg %>%
  filter(label %in% names(labels))

plot <- ggplot(df_subset, aes(output_len, fill = label)) +
  geom_histogram(binwidth = 10) +
  geom_label(
    data = df_agg_subset, mapping = aes(label = sprintf("x̄ = %s\nMSE = %s\np = %s", round(avg), round(mse), round(pval, 3)), color = label, x = 20, y = Inf),
    vjust = 1.1, hjust = 0, fill = "white",
    family = "Overpass",
    size = 2, lineheight = 1.0, label.padding = unit(0.10, "cm"), label.size = 0.3,
  ) +
  scale_x_continuous(limits = c(0, 400)) +
  geom_vline(xintercept = 200, color = "#1a1a1a") +
  scale_fill_manual(values = labels, guide = "none") +
  scale_color_manual(values = labels, guide = "none") +
  labs(
    title = "Distribution of Character Lengths of ChatGPT Output by Tip Incentive",
    subtitle = "100 generations each, targeting 200 characters. gpt-3.5-turbo-0125, temperature = 1",
    x = "Character Length of Generation", y = "# of Generations",
    caption = caption
  ) +
  facet_wrap(~label, nrow = 3)

ggsave("tips_hist_pos.png", plot, width = 4, height = 4)
```

```{r}
labels <- c(
  "$500 fine" = palette[5],
  "$1,000 fine" = "#16a085",
  "$100,000 debt" = palette[7]
)

df_subset <- df %>%
  filter(label %in% names(labels)) %>%
  mutate(label = factor(label, levels = names(labels)))

df_agg_subset <- df_agg %>%
  filter(label %in% names(labels))

plot <- ggplot(df_subset, aes(output_len, fill = label)) +
  geom_histogram(binwidth = 10) +
  geom_label(
    data = df_agg_subset, mapping = aes(label = sprintf("x̄ = %s\nMSE = %s\np = %s", round(avg), round(mse), round(pval, 3)), color = label, x = 20, y = Inf),
    vjust = 1.1, hjust = 0, fill = "white",
    family = "Overpass",
    size = 2, lineheight = 1.0, label.padding = unit(0.10, "cm"), label.size = 0.3,
  ) +
  scale_x_continuous(limits = c(0, 400)) +
  geom_vline(xintercept = 200, color = "#1a1a1a") +
  scale_fill_manual(values = labels, guide = "none") +
  scale_color_manual(values = labels, guide = "none") +
  labs(
    title = "Distribution of Character Lengths of ChatGPT Output by Tip Incentive",
    subtitle = "100 generations each, targeting 200 characters. gpt-3.5-turbo-0125, temperature = 1",
    x = "Character Length of Generation", y = "# of Generations",
    caption = caption
  ) +
  facet_wrap(~label, nrow = 3)

ggsave("tips_hist_neg.png", plot, width = 4, height = 4)
```

Advanced:

```{r}
temp_palette <- viridis(9, option = "viridis")
labels <- c(
  "Taylor Swift" = temp_palette[1],
  "World Peace" = temp_palette[2],
  "Mother" = temp_palette[3],
  "Love" = temp_palette[4],
  "Heaven" = temp_palette[5],
  "Chocolate" = temp_palette[6]
)

df_subset <- df %>%
  filter(label %in% names(labels)) %>%
  mutate(label = factor(label, levels = names(labels)))

df_agg_subset <- df_agg %>%
  filter(label %in% names(labels))

plot <- ggplot(df_subset, aes(output_len, fill = label)) +
  geom_histogram(binwidth = 10) +
  geom_label(
    data = df_agg_subset, mapping = aes(label = sprintf("x̄ = %s\nMSE = %s\np = %s", round(avg), round(mse), round(pval, 3)), color = label, x = 20, y = Inf),
    vjust = 1.1, hjust = 0, fill = "white",
    family = "Overpass",
    size = 2, lineheight = 1.0, label.padding = unit(0.10, "cm"), label.size = 0.3,
  ) +
  scale_x_continuous(limits = c(0, 400)) +
  geom_vline(xintercept = 200, color = "#1a1a1a") +
  scale_fill_manual(values = labels, guide = "none") +
  scale_color_manual(values = labels, guide = "none") +
  labs(
    title = "Distribution of Character Lengths of ChatGPT Output by Tip Incentive",
    subtitle = "100 generations each, targeting 200 characters. gpt-3.5-turbo-0125, temperature = 1",
    x = "Character Length of Generation", y = "# of Generations",
    caption = caption
  ) +
  facet_wrap(~label, nrow = 3)

ggsave("tips_hist_pos_adv.png", plot, width = 4, height = 4)
```

```{r}
temp_palette <- viridis(9, option = "plasma")
labels <- c(
  "Death (nocaps)" = temp_palette[1],
  "DEATH (CAPS)" = temp_palette[2],
  "COVID-19" = temp_palette[3],
  "Weight" = temp_palette[4],
  "Job" = temp_palette[5],
  "Friends" = temp_palette[6]
)

df_subset <- df %>%
  filter(label %in% names(labels)) %>%
  mutate(label = factor(label, levels = names(labels)))

df_agg_subset <- df_agg %>%
  filter(label %in% names(labels))

plot <- ggplot(df_subset, aes(output_len, fill = label)) +
  geom_histogram(binwidth = 10) +
  geom_label(
    data = df_agg_subset, mapping = aes(label = sprintf("x̄ = %s\nMSE = %s\np = %s", round(avg), round(mse), round(pval, 3)), color = label, x = 20, y = Inf),
    vjust = 1.1, hjust = 0, fill = "white",
    family = "Overpass",
    size = 2, lineheight = 1.0, label.padding = unit(0.10, "cm"), label.size = 0.3,
  ) +
  scale_x_continuous(limits = c(0, 400)) +
  geom_vline(xintercept = 200, color = "#1a1a1a") +
  scale_fill_manual(values = labels, guide = "none") +
  scale_color_manual(values = labels, guide = "none") +
  labs(
    title = "Distribution of Character Lengths of ChatGPT Output by Tip Incentive",
    subtitle = "100 generations each, targeting 200 characters. gpt-3.5-turbo-0125, temperature = 1",
    x = "Character Length of Generation", y = "# of Generations",
    caption = caption
  ) +
  facet_wrap(~label, nrow = 3)

ggsave("tips_hist_neg_adv.png", plot, width = 4, height = 4)
```

## Combos

```{r}
df_combos <- read_csv("tips_trial_combos.csv")
df_combos %>% head()
```

```{r}
pos_labels <- c(
  "<no tip>",
  "$500 tip",
  "$1,000 tip",
  "$100,000 bonus",
  "Taylor Swift",
  "World Peace",
  "Mother",
  "Love",
  "Heaven",
  "Chocolate"
)

neg_labels <- c(
  "<no tip>",
  "$500 fine",
  "$1,000 fine",
  "$100,000 debt",
  "Death (nocaps)",
  "DEATH (CAPS)",
  "COVID-19",
  "Weight",
  "Job",
  "Friends"
)
```

```{r}
df_combos_agg <- df_combos %>%
  mutate(label_pos = factor(label_pos), label_neg = factor(label_neg)) %>%
  group_by(label_pos, label_neg) %>%
  summarize(
    avg = mean(output_len),
    std = sd(output_len),
    mse = mean((output_len - 200)^2),
  )

df_combos_agg %>% head()
```

Convert the old aggregation tables to be compatable with the combo table.

```{r}
df_agg_subset_pos <- df_agg %>%
  filter(label %in% pos_labels) %>%
  mutate(label_neg = "<no tip>") %>%
  select(label_pos = label, label_neg, avg, std, mse)

df_agg_subset_neg <- df_agg %>%
  filter(label %in% neg_labels[-1]) %>%
  mutate(label_pos = "<no tip>") %>%
  select(label_pos, label_neg = label, avg, std, mse)

df_combos_agg <- df_combos_agg %>%
  bind_rows(df_agg_subset_pos) %>%
  bind_rows(df_agg_subset_neg) %>%
  mutate(
    label_pos = factor(label_pos, levels = pos_labels),
    label_neg = factor(label_neg, levels = neg_labels)
  )


df_combos_agg %>% nrow()
```

```{r}
plot <- ggplot(df_combos_agg, aes(x = label_pos, y = label_neg, fill = mse)) +
  geom_raster(stat = "identity", interpolate = FALSE) +
  scale_x_discrete() +
  scale_y_discrete() +
  scale_fill_viridis_c(option = "inferno") +
  labs(
    title = "Accuracy of ChatGPT Output by Tip/Threat Incentives",
    subtitle = "Targeting 200 characters. gpt-3.5-turbo-0125, temperature = 1",
    x = "Positive Incentives", y = "Negative Incentives", fill = "Mean Square Error\n(lower is better)",
    caption = caption
  ) +
  theme(
    legend.position = "top",
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 5, margin = margin(c(0.0, 0.5, 0.0, 0.), unit = "cm")),
    legend.key.width = unit(0.75, unit = "cm"),
    legend.key.height = unit(0.25, unit = "cm"),
    legend.margin = margin(c(0.0, 0.5, -0.1, 0.4), unit = "cm"),
    axis.text.x = element_text(size = 6, angle = -45, vjust = -1, color = "#1a1a1a", face = "plain"),
    axis.text.y = element_text(size = 6, color = "#1a1a1a", face = "plain"),
  )

ggsave("tips_tile_mse.png", plot, width = 4, height = 4)
```

```{r}
best_combos <- df_combos_agg %>%
  arrange(mse) %>%
  head() %>%
  mutate(label = paste0(label_pos, " / ", label_neg))

label_order <- best_combos$label

best_combos <- best_combos %>%
  mutate(label = factor(label, levels = label_order))

best_combos
```

```{r}
df_combo_subset <- df_combos %>%
  left_join(best_combos) %>%
  filter(!is.na(mse)) %>%
  mutate(
    label = factor(label, levels = label_order),
    label_pos = factor(label_pos, levels = pos_labels),
    label_neg = factor(label_neg, levels = neg_labels)
  )

plot <- ggplot(df_combo_subset, aes(output_len, fill = label)) +
  geom_histogram(binwidth = 10) +
  geom_label(
    data = best_combos, mapping = aes(label = sprintf("x̄ = %s\nMSE = %s", round(avg), round(mse)), color = label, x = 20, y = Inf),
    vjust = 1.1, hjust = 0, fill = "white",
    family = "Overpass",
    size = 2, lineheight = 1.0, label.padding = unit(0.10, "cm"), label.size = 0.3,
  ) +
  scale_x_continuous(limits = c(0, 400)) +
  scale_y_continuous(breaks = seq(0, 14, 2)) +
  geom_vline(xintercept = 200, color = "#1a1a1a") +
  scale_fill_viridis_d(option = "inferno", guide = "none", end = 0.8) +
  scale_color_viridis_d(option = "inferno", guide = "none", end = 0.8) +
  labs(
    title = "Distribution of Character Lengths of ChatGPT Output by Tip Incentive",
    subtitle = "30 generations each, targeting 200 characters. gpt-3.5-turbo-0125, temperature = 1",
    x = "Character Length of Generation", y = "# of Generations",
    caption = caption
  ) +
  facet_wrap(~label, nrow = 3)

ggsave("tips_hist_combos.png", plot, width = 4, height = 4)
```